name: Build and Push React Application to ACR

on:
  push:
    branches: [ master ]

env: 
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # ❌ SUPPRIMÉ : Log in to Azure (pas besoin sans Service Principal)
      
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login \
            ${{ secrets.ACR_NAME }}.azurecr.io \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
      
      - name: Push image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      # ❌ SUPPRIMÉ : Configure Container App registry credentials (vous le ferez manuellement une fois)
      # ❌ SUPPRIMÉ : Deploy to Azure Container Apps (vous le ferez manuellement)
      # ❌ SUPPRIMÉ : Restart Container App (vous le ferez manuellement)
      
      - name: ✅ Build successful - Manual deployment required
        run: |
          echo "========================================="
          echo "✅ Image successfully built and pushed!"
          echo "========================================="
          echo ""
          echo "📦 Image: ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo ""
          echo "🚀 To deploy, run these commands from your local machine:"
          echo ""
          echo "# 1. Configure registry credentials (only needed once)"
          echo "az containerapp registry set \\"
          echo "  --name ${{ secrets.CONTAINERAPP_NAME }} \\"
          echo "  --resource-group ${{ secrets.RESOURCE_GROUP }} \\"
          echo "  --server ${{ secrets.ACR_NAME }}.azurecr.io \\"
          echo "  --username ${{ secrets.ACR_USERNAME }} \\"
          echo "  --password \$ACR_PASSWORD"
          echo ""
          echo "# 2. Deploy the new image"
          echo "az containerapp update \\"
          echo "  --name ${{ secrets.CONTAINERAPP_NAME }} \\"
          echo "  --resource-group ${{ secrets.RESOURCE_GROUP }} \\"
          echo "  --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          echo ""
          echo "# 3. Restart to pull the latest image"
          echo "az containerapp revision restart \\"
          echo "  --name ${{ secrets.CONTAINERAPP_NAME }} \\"
          echo "  --resource-group ${{ secrets.RESOURCE_GROUP }} \\"
          echo "  --revision \$(az containerapp revision list --name ${{ secrets.CONTAINERAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query '[0].name' -o tsv)"
          echo ""
          echo "========================================="